name: publish
run-name: "Publish ${{ github.event.inputs.version }} 🤖"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Updated package version'
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Validate version format
        run: |
          if [[ ! ${{ github.event.inputs.version }} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Version '${{ github.event.inputs.version }}' is not a valid semver version."
            exit 1
          fi

      - name: Checkout repository source
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: '10.x'

      - name: Configure git
        run: |
          git config --global user.name "Kruithne"
          git config --global user.email "kruithne@gmail.com"

      - name: Install dependencies
        run: npm ci
        
      - name: Compile Greenworks
        run: npm run compdb

      - name: Update package version
        run: npm version ${{ github.event.inputs.version }} -m "Release ${{ github.event.inputs.version }} ✨"

      - name: Push changes
        run: git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release tarball
        run: npm pack --output=release-${{ github.event.inputs.version }}.tgz

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release-${{ github.event.inputs.version }}.tgz
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          body: |
            Release ${{ github.event.inputs.version }} ✨